### ISSUE TITLE
World loading freezes on any %

### ISSUE THREAD

**Issue by PollusS** [Ladysnake/Astronomical#13] opened 2024-01-18 13:50 UTC
![image](https://github.com/Ladysnake/Astronomical/assets/157029629/d8c63139-8bcd-4c49-807e-978b6ea1ae29)
I only have Quilted Fabric Api and Quilt Standard Libraries and Astronomical. But for some reason when i try creating a new world the loading just stops and never ends. When i try joining already created world, i get message "Invalid player data". Anyone knows on how to fix it?
![image](https://github.com/Ladysnake/Astronomical/assets/157029629/c94481fe-d20b-4f6b-806b-31929c8eb3c1)

**Comment by UpcraftLP** [comment] 2024-01-18 13:55
Duplicate of #1

to fix it, install Cardinal Components API.

**Closed as not planned by UpcraftLP** 2024-01-18 13:55 UTC
Labels: duplicate
