### ISSUE TITLE
[Bug Report] Game crashing when placing Create schematics and when the "ponder" screen is opened

### ISSUE THREAD

**Issue by MintySweeteaReal** [Ladysnake/Astronomical#19] opened 2024-01-22 21:10 UTC
When trying to open the pondering screen or when placing a schematic with Astronomical and Create fabric installed the game will briefly freeze, then go to the "Saving World" screen for a few seconds after which the game crashes.

[create schematic crash report.txt](https://github.com/Ladysnake/Astronomical/files/14015449/create.schematic.crash.report.txt)

**Comment by Pyrofab** [comment] 2024-01-22 21:25
Duplicate of #6

**Closed as not planned by Pyrofab** 2024-01-22 21:25 UTC
