### ISSUE TITLE
Minecraft appears to "crash" when creating a world with the mod.

### ISSUE THREAD

**Issue by KeenanAxolotl** [Ladysnake/Astronomical#18] opened 2024-01-22 07:50 UTC
Trying to load into a world while playing with the mod freezes on the loading screen, and the window can only be closed with Task Manager. The only mods I'm using are this one and Quilted Fabric Loader (which is listed as a dependency by Quilt.)
![Screenshot (35)](https://github.com/Ladysnake/Astronomical/assets/87741594/ab7f4ac0-5a8c-4faa-937a-3873b4d38530)

The loading screen freezes here:
![Screenshot (36)](https://github.com/Ladysnake/Astronomical/assets/87741594/8f55d665-2e98-4f2e-a837-0acca26e86fd)

Version of Quilt:
![Screenshot (37)](https://github.com/Ladysnake/Astronomical/assets/87741594/be2a558f-2cda-4dcb-904d-8d29f2c8d610)

(Sorry if this is a problem with my system, I'm not sure where else to ask!)

**Comment by Pyrofab** [comment] 2024-01-22 07:51
Duplicate of #1

**Closed as not planned by Pyrofab** 2024-01-22 07:51 UTC
