### ISSUE TITLE
Crashes on launch with QFAPI 4.0.0-beta.30+0.77.0-1.19.2

### ISSUE THREAD

**Issue by Poopooracoocoo** [Ladysnake/Astronomical#26] opened 2024-05-01 04:54 UTC
### Environment
[Astronomical 1.0.1+1.19.2](https://modrinth.com/mod/astronomical/version/1.0.1+1.19.2)
[Cardinal Components API 5.0.2](https://modrinth.com/mod/cardinal-components-api/version/5.0.2)
QFAPI 4.0.0-beta.30+0.77.0-1.19.2
Quilt Loader 0.26 beta
Prism Launcher 8.3

### Log

[latest.log](https://github.com/Ladysnake/Astronomical/files/15173852/latest.log)

### Crash report

[crash-2024-05-01_14.45.57-client.txt](https://github.com/Ladysnake/Astronomical/files/15173855/crash-2024-05-01_14.45.57-client.txt)

### Notes

The lines to look at are these:
> `Caused by: net.minecraft.class_2973: Invalid shaders/core/particle.json: Non [a-z0-9/._-] character in path of location: lodestone:lodestone:shaders/core/particle.vsh`

> `Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: lodestone:lodestone:shaders/core/particle.vsh`

This is because Lodestone Lib, which is included in Astronomical, does not support Fabric API 0.77.0 which adds <https://github.com/FabricMC/fabric/pull/3413>

Until this is addressed, users can get it to work by downgrading Fabric API to 0.76.x by downgrading QFAPI: <https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2>

**Comment by UpcraftLP** [comment] 2024-05-01 08:43
Duplicate of #21, you need to downgrade QFAPI.

**Closed as not planned by UpcraftLP** 2024-05-01 08:43 UTC
Labels: duplicate

**Comment by Poopooracoocoo** [comment] 2024-05-01 11:09
I'm aware you can downgrade FAPI but the other issue was closed as "completed", and this issue was closed as a duplicate. So is making your mod compatible with FAPI 0.77 not planned?

**Comment by Pyrofab** [comment] 2024-05-01 11:13
Right, yes unfortunately maintaining Astronomical is not a big priority of ours, and fixing MC 1.19.2 versions of our mods even less so. The next version of Astronomical is most likely going to be on 1.20.1 or later - the issue will be fixed there.
